//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora.WSListadoPorTipoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOListadoPorTipo", Namespace="http://schemas.datacontract.org/2004/07/DistribuidoraServicios")]
    [System.SerializableAttribute()]
    public partial class DTOListadoPorTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantMinimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioSugeridoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TiempoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantMinima {
            get {
                return this.CantMinimaField;
            }
            set {
                if ((this.CantMinimaField.Equals(value) != true)) {
                    this.CantMinimaField = value;
                    this.RaisePropertyChanged("CantMinima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisOrigen {
            get {
                return this.PaisOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisOrigenField, value) != true)) {
                    this.PaisOrigenField = value;
                    this.RaisePropertyChanged("PaisOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioSugerido {
            get {
                return this.PrecioSugeridoField;
            }
            set {
                if ((this.PrecioSugeridoField.Equals(value) != true)) {
                    this.PrecioSugeridoField = value;
                    this.RaisePropertyChanged("PrecioSugerido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tiempo {
            get {
                return this.TiempoField;
            }
            set {
                if ((this.TiempoField.Equals(value) != true)) {
                    this.TiempoField = value;
                    this.RaisePropertyChanged("Tiempo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSListadoPorTipoReference.IServicioListadoPorTipo")]
    public interface IServicioListadoPorTipo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioListadoPorTipo/listadoFabricados", ReplyAction="http://tempuri.org/IServicioListadoPorTipo/listadoFabricadosResponse")]
        Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[] listadoFabricados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioListadoPorTipo/listadoFabricados", ReplyAction="http://tempuri.org/IServicioListadoPorTipo/listadoFabricadosResponse")]
        System.Threading.Tasks.Task<Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[]> listadoFabricadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioListadoPorTipo/listadoImportados", ReplyAction="http://tempuri.org/IServicioListadoPorTipo/listadoImportadosResponse")]
        Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[] listadoImportados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioListadoPorTipo/listadoImportados", ReplyAction="http://tempuri.org/IServicioListadoPorTipo/listadoImportadosResponse")]
        System.Threading.Tasks.Task<Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[]> listadoImportadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioListadoPorTipoChannel : Distribuidora.WSListadoPorTipoReference.IServicioListadoPorTipo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioListadoPorTipoClient : System.ServiceModel.ClientBase<Distribuidora.WSListadoPorTipoReference.IServicioListadoPorTipo>, Distribuidora.WSListadoPorTipoReference.IServicioListadoPorTipo {
        
        public ServicioListadoPorTipoClient() {
        }
        
        public ServicioListadoPorTipoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioListadoPorTipoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioListadoPorTipoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioListadoPorTipoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[] listadoFabricados() {
            return base.Channel.listadoFabricados();
        }
        
        public System.Threading.Tasks.Task<Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[]> listadoFabricadosAsync() {
            return base.Channel.listadoFabricadosAsync();
        }
        
        public Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[] listadoImportados() {
            return base.Channel.listadoImportados();
        }
        
        public System.Threading.Tasks.Task<Distribuidora.WSListadoPorTipoReference.DTOListadoPorTipo[]> listadoImportadosAsync() {
            return base.Channel.listadoImportadosAsync();
        }
    }
}
