//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora.ServiceReferenceListadoProdFab {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOListadoProdFab", Namespace="http://schemas.datacontract.org/2004/07/DistribuidoraServicios")]
    [System.SerializableAttribute()]
    public partial class DTOListadoProdFab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceListadoProdFab.IListadoProdFabService")]
    public interface IListadoProdFabService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListadoProdFabService/listado", ReplyAction="http://tempuri.org/IListadoProdFabService/listadoResponse")]
        Distribuidora.ServiceReferenceListadoProdFab.DTOListadoProdFab[] listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListadoProdFabService/listado", ReplyAction="http://tempuri.org/IListadoProdFabService/listadoResponse")]
        System.Threading.Tasks.Task<Distribuidora.ServiceReferenceListadoProdFab.DTOListadoProdFab[]> listadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListadoProdFabServiceChannel : Distribuidora.ServiceReferenceListadoProdFab.IListadoProdFabService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListadoProdFabServiceClient : System.ServiceModel.ClientBase<Distribuidora.ServiceReferenceListadoProdFab.IListadoProdFabService>, Distribuidora.ServiceReferenceListadoProdFab.IListadoProdFabService {
        
        public ListadoProdFabServiceClient() {
        }
        
        public ListadoProdFabServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListadoProdFabServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListadoProdFabServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListadoProdFabServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Distribuidora.ServiceReferenceListadoProdFab.DTOListadoProdFab[] listado() {
            return base.Channel.listado();
        }
        
        public System.Threading.Tasks.Task<Distribuidora.ServiceReferenceListadoProdFab.DTOListadoProdFab[]> listadoAsync() {
            return base.Channel.listadoAsync();
        }
    }
}
